Generate /etc/hosts and /etc/resolv.conf when tunnelling to host network

diff --git a/agent-sandbox b/agent-sandbox
--- a/agent-sandbox
+++ b/agent-sandbox
@@ -135,15 +135,28 @@ bwrap_args=(
   --unshare-all
 )
 
-if [ -n "${host_name}" ] ; then
-    bwrap_args+=( --hostname "${host_name}" )
-fi
-
 # Enable networking if requested.
 # (For "tunnelling", bwrap inherits not the host's network namespace 
 #  but the network namespace set up by pasta, below.)
-if [ "$share_net" -ne 0 ] || [ "$tunnel_net" -ne 0 ] ; then
+if [ "$share_net" -ne 0 ] ; then
+    bwrap_args+=( --share-net --share-uts )
+
+    # Use host's existing configuration for all machine names
+    #config_whitelist+=( "/etc/hosts" "/etc/resolv.conf" )
+
+    # And therefore we must disallow overriding the sandbox's machine name,
+    # because any new name would be inconsistent with the existing files above.
+    if [ -n "${host_name}" -ne 0 ] ; then
+        echo >&2 "$0: cannot override host name of sandbox when sharing existing network"
+        exit 1
+    fi
+
+elif [ "$tunnel_net" -ne 0 ] ; then
     bwrap_args+=( --share-net )
+fi
+
+if [ -n "${host_name}" ] ; then
+    bwrap_args+=( --hostname "${host_name}" )
 fi
 
 bwrap_args+=( 
@@ -165,6 +178,9 @@ bwrap_args+=(
   --symlink ../run/lock /var/lock
   --symlink ../tmp /var/tmp
   --tmpfs /var/cache
+
+  # Create container for dynamically-generated /etc files
+  --dir /etc
 
   # Set up base home directory that is writable since many tools/apps depend on that.
   # Note that except for explicitly bind-mounted "work" directories, changes 
@@ -251,9 +267,6 @@ if [ -n "${env_file}" ] ; then
     fi
 fi
 
-# Seal the root filesystem to be read-only after all modifications
-bwrap_args+=( --remount-ro / )
-
 
 
 # N.B. According to bwrap's documentation, the current directory in the sandbox is 
@@ -267,9 +280,11 @@ fi
 
 
 if [ "$tunnel_net" -eq 0 ] ; then
+    # Seal the root filesystem to be read-only after all modifications
+    bwrap_args+=( --remount-ro / )
 
     # Run bwrap with set-up arguments sent on FD 9
-    "$bwrap_path" --args 9 -- "$@" 9< <(printf '%s\0' "${bwrap_args[@]}") || exit $?
+    "$bwrap_path" --args 137 -- "$@" 137< <(printf '%s\0' "${bwrap_args[@]}") || exit $?
 
 else
 
@@ -311,8 +326,58 @@ else
     target_uid=$(id -u)
     target_gid=$(id -g)
 
-    "$pasta_path" --config-net --ns-ifname sandbox_tap --no-dhcp -- \
-        "$bwrap_path" --uid $target_uid --gid $target_gid "${bwrap_args[@]}" -- "$@" 
+    bwrap_args+=( --uid $target_uid --gid $target_gid )
+    
+    bwrap_args+=( --perms 400 --bind-data 138 /etc/resolv.conf )
+    bwrap_args+=( --perms 400 --bind-data 139 /etc/hosts )
+
+    if [ -z "${host_name}" ] ; then 
+        host_name="$(/bin/hostname)"
+        host_name="${host_name:-agent-sandbox}"
+        bwrap_args+=( --hostname ${host_name} )
+    fi
+
+    bwrap_args+=( --remount-ro / )
+
+    # Prepare to write temporary files for data to pass to bwrap.
+    #
+    # We cannot pass file descriptors to bwrap because pasta calls close_range(2) at start-up
+    # --- as a deliberate security measure to prevent leaks into containers, 
+    # but breaks our use case.
+    tmp_dir="$(mktemp -d -t "$(basename "$0")-XXXXXX")"
+    trap 'rm -rf "$tmp_dir"' exit
+
+    # Write arguments to temporary file
+    printf '%s\0' "${bwrap_args[@]}" > "$tmp_dir/bwrap_args"
+
+    # Generate /etc/resolv.conf pointing to pasta's DNS forwarder
+    cat > "$tmp_dir/resolv.conf" <<EOF
+nameserver fe80::1
+nameserver 169.254.0.1
+EOF
+
+    # Generate /etc/hosts containing the host name that was set
+    cat > "$tmp_dir/hosts" <<EOF
+::1         localhost 
+127.0.0.1   localhost
+fe80::2     ${host_name}
+169.254.0.2 ${host_name}
+
+EOF
+
+    "$pasta_path" \
+        --address 169.254.0.2/16 --gateway 169.254.0.1 --dns-forward 169.254.0.1 \
+        --address fe80::2/10 --gateway fe80::1 --dns-forward fe80::1 \
+        --config-net --ns-ifname sandbox_tap --no-dhcp -- \
+        /bin/bash -c '
+            tmp_dir="$1"
+            shift
+            exec 137< "$tmp_dir/bwrap_args"
+            exec 138< "$tmp_dir/resolv.conf"
+            exec 139< "$tmp_dir/hosts"
+            rm -f "$tmp_dir/bwrap_args" "$tmp_dir/resolv.conf" "$tmp_dir/hosts"
+            exec bwrap --args 137 -- "$@" 
+        ' _bwrap.sh "$tmp_dir" "$@"
 
 fi
 
